---
title: "Ben's Home"
self_contained: truehttps://opportunityinsights.org/wp-content/uploads/2023/07/CollegeAdmissions_Nontech.pdf?campaign_id=9&emc=edit_nn_20230724&instance_id=98292&nl=the-morning&regi_id=193353144&segment_id=140117&te=1&user_id=3df1c13f67c1cc50465f5cc2ad3445f5
---

<!-- make a button -->
<button onclick="location.href='https://docs.google.com/document/d/1vYE5fymvYNpyUVd9APUqRUy3BS3_jatqYiXHDwDIgfM/edit'" type="button" style="background-color: #273ec2; color: white; padding: 10px 20px;border-radius: 12px;  border: none;">
Angela Checkins
</button>

<button onclick="location.href='https://docs.google.com/spreadsheets/d/1cuRdXy_Ygj9w3IASRL6ZLEFNn8vclvKzmSXdH6ITukI/edit#gid=0'" type="button" style="background-color: #273ec2; color: white; padding: 10px 20px;border-radius: 12px;  border: none;
">
Weekly Planning
</button>

<button onclick="location.href='https://docs.google.com/document/d/13s6nx6HYiW9trQQB7W-npEARN91ONd9QzYcLF39yqrs/edit'" type="button" style="background-color: #273ec2; color: white; padding: 10px 20px;border-radius: 12px;  border: none;
">
Thoughts
</button>

<button onclick="location.href='https://lirabenjamin.github.io/home/gratitude_journal.html'" type="button" style="background-color: #273ec2; color: white; padding: 10px 20px;border-radius: 12px;  border: none;
">
Gratitude
</button>

# Upcoming deadlines

<script src="https://cdn.logwork.com/widget/countdown.js"></script>
<a href="https://logwork.com/countdown-1a4u" class="countdown-timer" data-style="columns" data-timezone="America/New_York" data-date="2023-11-06 13:30">Duckworth Milkman Lab Meeting: Nov 6 13:30</a>

<script src="https://cdn.logwork.com/widget/countdown.js"></script>
<a href="https://logwork.com/countdown-1a4u" class="countdown-timer" data-style="columns" data-timezone="America/New_York" data-date="2023-11-13 23:59">Third Year Paper Proposals: Nov 13 23:59</a>

# Active projects

## 1. Personal qualities
- In Press
- I should write some social media posts about it.

## 2. COVID GPA
Waiting on RnR - Under review. 
- Email them a month from now if I haven't heard anything. September 23

## [3. Effect sizes](https://lirabenjamin.github.io/effect-size)
- To write and accept proposal
- Get all emails (Dan is on it)
- email authors for data
- analyze data

1. What are people doing
- Get more pdfs
- Refine dictionaries / train transformer
  
1. What is the correction
- get datasets from osf
- process metadat and psymetadata data
- run robma on everything

- get more emails
- email people
- process their data
- run robma on everything 

- Data should be coded for covariates: social/cognitive, lab/field, cross-sectional/longitudinal, methodvariance

1. What do researchers think about it
- Make a quick mail and question
- Find sampling strategy
- Sample people at SPSP?

1. No bias in DoE data
- Get that data from Matt Kraft
- Run robma on it

## [4. Role models](https://lirabenjamin.github.io/rolemodels)
- Write up S1 results cleanly
- S2: Running a fully powered study: Figure out pre-reg and qualtrics
- Plan out S3 to present to lab meeting
  
*Later*
- Analyze S2
- Write up S2 results
- Intro and discussion

## 5. Khan Academy intervention
- Revieweing DUA comments
- Potential Launch Date:  

## 6. Khan Academy with Stef
- Waiting on KHan Team for approval
- Email them results from our Saturday conversation.

## 7. MiniKhanmigo
- See it live here for [situation modification](http://reframe001-7a186c892e5e.herokuapp.com/?condition=situation) and [emotion reframing](http://reframe001-7a186c892e5e.herokuapp.com/?condition=emotion). (DO NOT ABUSE)
- Finalize qualtrics pilot

# Backlog of ideas
- Does writing with chatGPT increase or decrease the amount of information you can get when measuring psychological traits.
- What are some potential good consequences of chatGPT being like a person but not being a person.
  - Are you less or more defensive when getting feedback from chatGPT?
- Does interacting with a chatbot make you less careful at work?
- Do we improve on our personal qualities paper by modelling judge fixed effects, or judge fatigue, or time of day?
- Does GPT perform better at pairwise comparison than 1/5 rating?
- The overreliance problem... How much should I read the code given by chatGPT and try to learn from it, vs. how much should I delegate. Just be quicker. There is a tradeoff between learning and speed. I can see some cases where this leads to a hyperbolic discounting problem.
- Absenses are increasing throuought after covid. People did not go back to regular in-person. Student absenteeism is way up, adults are not back at their jobs, older people are not going back to church. Is there a way to show generalized diminishes in real-life attendance to in-person events and social interaction. Loneliness epidemic framing.